CUSTOM_DATE_YEAR := $(shell date -u +%Y)
CUSTOM_DATE_MONTH := $(shell date -u +%m)
CUSTOM_DATE_DAY := $(shell date -u +%d)
CUSTOM_DATE_HOUR := $(shell date -u +%H)
CUSTOM_DATE_MINUTE := $(shell date -u +%M)
CUSTOM_BUILD_DATE := $(CUSTOM_DATE_YEAR)$(CUSTOM_DATE_MONTH)$(CUSTOM_DATE_DAY)-$(CUSTOM_DATE_HOUR)$(CUSTOM_DATE_MINUTE)

PRODUCT_VERSION_MAJOR = 9
PRODUCT_VERSION_MINOR = 0
PRODUCT_VERSION_MAINTENANCE := 0

# values RELEASE NIGHTLY EXPERIMENTAL
PROJECT_NEMO_BUILDTYPE := EXPERIMENTAL

PROJECT_NEMO_VERSION := Project_Nemo.$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_MAINTENANCE)-$(PROJECT_NEMO_BUILDTYPE)

PROJECT_NEMO_FINGERPRINT := Project_Nemo/$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_MAINTENANCE)/$(CUSTOM_BUILD_DATE)

# PROJECT_NEMOOs System Version
PRODUCT_PROPERTY_OVERRIDES += \
    dz.nemo.version=$(PROJECT_NEMO_VERSION) \
    dz.nemo.release_type=$(PROJECT_NEMO_BUILDTYPE) \
    dz.nemo.build_date=$(CUSTOM_BUILD_DATE) \
    dz.nemo.fingerprint=$(PROJECT_NEMO_FINGERPRINT)